version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres_db}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

      ADMIN_DB_USER: ${ADMIN_DB_USER:-admindb_user}
      ADMIN_DB_PASSWORD: ${ADMIN_DB_PASSWORD:-hola1234}
      ADMIN_DB_NAME: ${ADMIN_DB_NAME:-admindb}

      CLIENT1_USER: ${CLIENT1_USER:-rsrv_client1_user}
      CLIENT1_PASSWORD: ${CLIENT1_PASSWORD:-hola1234}
      CLIENT1_NAME: ${CLIENT1_NAME:-rsrv_client1}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres_net

  #app:
  #  build:
  #    context: .
  #  container_name: reserva
  #  restart: unless-stopped
  #  env_file:
  #    - .env
  #  volumes:
  #    - .:/app
  #  ports:
  #    - "8000:8000"
  #  depends_on:
  #    - postgres
  #  networks:
  #    - app_net

volumes:
  postgres_data:
    driver: local

networks:
  app_net:
    driver: bridge
    
  postgres_net:
    driver: bridge