#!/bin/bash
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${ADMIN_DB_USER} WITH ENCRYPTED PASSWORD '${ADMIN_DB_PASSWORD}';
    CREATE DATABASE ${ADMIN_DB_NAME} OWNER ${ADMIN_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${ADMIN_DB_NAME} TO ${ADMIN_DB_USER};

    CREATE USER ${CLIENT1_USER} WITH ENCRYPTED PASSWORD '${CLIENT1_PASSWORD}';
    CREATE DATABASE ${CLIENT1_NAME} OWNER ${CLIENT1_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${CLIENT1_NAME} TO ${CLIENT1_USER};
EOSQL